(Rspec:graphql) WIP: add spec for CourseUpdate
FIXME:

Why input variable is wrongly typed?

/opt/homebrew/opt/ruby/bin/ruby -x /Users/unknowntpo/repo/unknowntpo/courses_manager/bin/bundle exec /opt/homebrew/opt/ruby/bin/ruby /opt/homebrew/lib/ruby/gems/3.2.0/bin/rspec /Users/unknowntpo/repo/unknowntpo/courses_manager/spec/graphql/mutations/course_update_spec.rb --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter --example "Mutations::CourseUpdate reorder chapters in a course should be reordered"
Testing started at 11:36 AM ...
Run options: include {:full_description=>/Mutations::CourseUpdate\ reorder\ chapters\ in\ a\ course\ should\ be\ reordered/}
variables: {
  "input": {
    "id": 311,
    "input": {
      "name": "C",
      "description": "Oh my god",
      "chapters": [
        {
          "id": 577,
          "courseId": 311,
          "position": 1
        },
        {
          "id": 578,
          "courseId": 311,
          "position": 0
        }
      ]
    }
  }
}
body: {"errors"=>[{"message"=>"Variable $input of type CourseUpdateInput! was provided invalid value for input.chapters.0.courseId (Could not coerce value \"311\" to Int), input.chapters.0.position (Could not coerce value \"1\" to Int), input.chapters.1.courseId (Could not coerce value \"311\" to Int), input.chapters.1.position (Could not coerce value \"0\" to Int)", "locations"=>[{"line"=>1, "column"=>29}], "extensions"=>{"value"=>{"id"=>"311", "input"=>{"name"=>"C", "description"=>"Oh my god", "chapters"=>[{"id"=>"577", "courseId"=>"311", "position"=>"1"}, {"id"=>"578", "courseId"=>"311", "position"=>"0"}]}}, "problems"=>[{"path"=>["input", "chapters", 0, "courseId"], "explanation"=>"Could not coerce value \"311\" to Int"}, {"path"=>["input", "chapters", 0, "position"], "explanation"=>"Could not coerce value \"1\" to Int"}, {"path"=>["input", "chapters", 1, "courseId"], "explanation"=>"Could not coerce value \"311\" to Int"}, {"path"=>["input", "chapters", 1, "position"], "explanation"=>"Could not coerce value \"0\" to Int"}]}}]}

NoMethodError: undefined method `[]' for nil:NilClass

  0) Mutations::CourseUpdate reorder chapters in a course should be reordered
     Failure/Error: data = body["data"]["courseUpdate"]["course"]

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/graphql/mutations/course_update_spec.rb:95:in `block (3 levels) in <module:Mutations>'
1 example, 1 failure, 0 passed
Finished in 0.236863 seconds